apiVersion: v1
kind: Service
metadata:
  name: crud-service
spec:
  selector:
    app: crud
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crud
  template:
    metadata:
      labels:
        app: crud
    spec:
      containers:
        - name: crud-api
          image: 
          ports:
            - containerPort: 80
          env:
            - name: CONNECTION_STRING
              value:  



